Dada la base de datos iris y sus características conocidas ¿Cuántas neuronas en la capa oculta son necesarias, como mínimo, en un multiperceptrón para lograr una clasificación aceptable? Realice un entrenamiento con la arquitectura elegida usando el 70% de los datos como conjunto de entrenamiento y mida la performance del modelo con el 30% restante.

In [27]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from bpn import train, plot

In [28]:
iris = pd.read_csv('../Practica 1/Iris.csv', sep = ";")

In [29]:
# Se unen las clases virginica y versicolor
iris["Clase"]= iris["Clase"].replace("Iris-setosa", 0)
iris["Clase"]= iris["Clase"].replace("Iris-versicolor", 1)
iris["Clase"]= iris["Clase"].replace("Iris-virginica", 2)

In [30]:
iris.head()

sepal length  sepal width  petal length  petal width  Clase
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [31]:
train_set, test_set = train_test_split(iris, test_size=0.3, random_state=320)

In [32]:
P = train_set[['sepal length', 'sepal width', 'petal length', 'petal width']].values

train_set['value'] = 1
T = train_set.pivot(columns = 'Clase', values = 'value').fillna(0).values

T2 = train_set[['Clase']].values
 

C:\Users\dalessam\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [33]:
#Parámetros:
#       P: es una matriz con los datos de los patrones con los cuales
#           entrenar la red neuronal. Los ejemplos deben estar en filas.
#       T: es una matriz con la salida esperada para cada ejemplo. Esta matriz 
#           debe tener tantas columnas como neuronas de salida tenga la red
#       T2: clases con su valor original (0 .. n-1) (Solo es utilizado para graficar)
#       ocultas: la cantidad de neuronas ocultas que tendrá la red    
#       alfa: velocidad de aprendizaje
#       momento: término de momento
#       fun_oculta: función de activación en las neuronas de la capa oculta
#       fun_salida: función de activación en las neuronas de la capa de salida
#       MAX_ITERA: la cantidad máxima de iteraciones en las cuales se va a
#           ejecutar el algoritmo
#       cota_error: diferencia de error (entre una iteración y la anterior) mínima aceptada para finalizar con el algoritmo
#       dibujar: si vale True (y los datos son en dos dimensiones) dibuja los
#           ejemplos y las rectas discriminantes.
#
#Devuelve:
#       w_O: la matriz de pesos de las neuronas de la capa oculta
#       b_O: vector de bias de las neuronas de la capa oculta
#       w_S: la matriz de pesos de las neuronas de la capa de salida
#       b_S: vector de bias de las neuronas de la capa de salida
#       ite: número de iteraciones ejecutadas durante el algoritmo
#       error_prom: errorPromedio finalizado el algoritmo
#
#Ejemplo de uso:
#       (w_O, b_O, w_S, b_S, ite, error_prom) = train(P, T, T2, 10, 0.25, 1.2, 'logsig', 'tansig', 25000, 0.001, True);

In [34]:
(w_O, b_O, w_S, b_S, ite, error_prom) = train(P, T, T2, 2, 0.01, 0, 'tansig', 'logsig', 100, 0.0001, True);

1 0.7788193098175245 0.22128069018247554
2 0.7443423661636309 0.03447694365389353
3 0.7240736551907616 0.020268710972869308
4 0.7110466042486391 0.013027050942122531
5 0.7012817775164767 0.00976482673216239
6 0.6936034599559877 0.007678317560488979
7 0.6875374492832782 0.00606601067270951
8 0.6827598298816532 0.004777619401625022
9 0.6790105500029953 0.0037492798786579185
10 0.6760783764867042 0.002932173516291048
11 0.673792948447246 0.0022854280394581927
12 0.6720174563254621 0.0017754921217839614
13 0.6706422862612907 0.001375170064171316
14 0.6695798978249442 0.0010623884363465397
15 0.6687607529830446 0.0008191448418995995
16 0.6681299942450857 0.0006307587379589252
17 0.6676446560372644 0.000485338207821262
18 0.6672713035733072 0.00037335246395719945
19 0.6669840531220688 0.00028725045123845216
20 0.6667629421554222 0.00022111096664656493
21 0.6665926131777499 0.00017032897767232935
22 0.666461268469595 0.0001313447081549013
23 0.6663598507563422 0.0001014177132527827
24 0.66628

In [35]:
w_O, b_O, w_S, b_S, ite, error_prom

(array([[ 0.47101976,  0.03437088, -0.06393194, -0.22789668],
        [ 0.15031867, -0.19282971,  0.17979147, -0.41161364]]),
 array([[0.12275122],
        [0.09151085]]),
 array([[-0.21410248,  0.15371549],
        [-0.35143002,  0.03050162],
        [-0.23975667, -0.34308572]]),
 array([[-0.76914431],
        [-0.38865695],
        [-0.01426247]]),
 100,
 0.6655527402061634)

In [36]:
testing = test_set[['sepal length', 'sepal width', 'petal length', 'petal width']]

In [37]:
def logsig(x):
    return 1 / (1 + np.exp(-x))

def dlogsig(x):
    return logsig(x) * (1 - logsig(x))

def tansig(x):
    return np.tanh(x)

def dtansig(x):
    return 1.0 - np.square(tansig(x))

In [38]:
# Calculo en test
neta_oculta = w_O.dot(testing.values.T) + b_O
salida_oculta = eval('tansig' + '(neta_oculta)')
neta_salida = w_S.dot(salida_oculta) + b_S
salida_salida = eval('logsig' + '(neta_salida)')
salida_salida

array([[0.2916874 , 0.28221357, 0.28393263, 0.29201807, 0.28619942,
        0.2870203 , 0.29175651, 0.29604975, 0.29035968, 0.29603714,
        0.28295595, 0.28220716, 0.28038163, 0.29060287, 0.28991834,
        0.28316586, 0.29021141, 0.28518976, 0.28953796, 0.29159761,
        0.28374326, 0.28601229, 0.28305706, 0.29184233, 0.29033195,
        0.29229519, 0.29261778, 0.29117811, 0.29223621, 0.28646385,
        0.29429974, 0.28969716, 0.28916472, 0.2826484 , 0.29152529,
        0.29538963, 0.28250786, 0.28098501, 0.29430836, 0.29436151,
        0.28972243, 0.28200533, 0.29196746, 0.28590872, 0.28897752],
       [0.32768317, 0.32625194, 0.32651308, 0.32819169, 0.32706964,
        0.32744122, 0.32817088, 0.32851185, 0.32806734, 0.32850939,
        0.32661062, 0.3255804 , 0.32572538, 0.32777758, 0.32803674,
        0.32610193, 0.32793137, 0.32689653, 0.32762285, 0.32793752,
        0.32669286, 0.32771051, 0.32707707, 0.32784279, 0.32838303,
        0.32879739, 0.3284278 , 0.32858324, 0.3

In [39]:
salida = pd.DataFrame(salida_salida.T)

In [40]:
salida.head()

0         1         2
0  0.291687  0.327683  0.386290
1  0.282214  0.326252  0.412571
2  0.283933  0.326513  0.407720
3  0.292018  0.328192  0.386539
4  0.286199  0.327070  0.401919

In [41]:
#testing['1'] = 0
#testing['2'] = 0
#testing['3'] = 0
#
#for index,row in testing.iterrows():
#    neta_oculta = w_O.dot(row[0:4].values[np.newaxis].T) + b_O
#    salida_oculta = eval('tansig' + '(neta_oculta)')
#    neta_salida = w_S.dot(salida_oculta) + b_S
#    salida_salida = eval('logsig' + '(neta_salida)')
#    testing.loc[index,'1'] = salida_salida[0] 
#    testing.loc[index,'2'] = salida_salida[1] 
#    testing.loc[index,'3'] = salida_salida[2] 
#
#testing

In [ ]:
# Con 2 da bastante bien